setup/urls.py

from django.contrib import admin
from django.urls import path,include
from estoque import views as v
from cliente import views as c
from servico import views as s
from transacao import views as t
from cliente.views import ClientListView, ClientCreateView, ClientDeleteView, ClientUpdateView
from estoque.views import ProdutoList, ProdutoCreateView, CategoriaCreateView, EntradaCreateView, SaidaCreateView, SaidaListView, EntradaListView, calcularsaida, graficos,UpdateView,vendas
from transacao.views import orcamento,TransacaoListView,transacao_detail, TransacaoDeleteView,FornecedorCreateView,FornecedorListView, VendaCreateView


urlpatterns = [
    #urls admin
    path('admin/', admin.site.urls),
    path('/accounts/login/', admin.site.urls),

    #URLS DO ESTOQUE
    path('estoque/', v.ProdutoList.as_view(), name="home_estoque"),
    path('estoque/grafico',v.calcularsaida, name='estoque_grafico'),
    path('ultimasvendas', v.vendas, name='ultimasvendas'),
    path ('estoque/cadastro', v.ProdutoCreateView.as_view(), name="cadastrar_produto"),
    path('servico/form_ordenservico', s.form_ordenservico, name="form_ordenservico"),
    path('atualiza_produto/<int:pk>', v.ProductUpdateView.as_view(), name="atualiza_produto"),
    path('delete/<int:pk>',v.ProductDeleteView.as_view(), name="delete_produto"),
    path ('estoque/cadastro_categoria', v.CategoriaCreateView.as_view(), name="cadastro_categoria"),
    path ('estoque/listar_categoria', v.CategoriaListView.as_view(), name="listar_categoria"),
    path('', v.home, name="home"),
    path('graficos', v.graficos, name="graficos"),
    path('estoque/entrada', EntradaCreateView.as_view(), name="criar_entrada_estoque"),
    path('estoque/saida', SaidaCreateView.as_view(), name="criar_saida_estoque"),
    path('estoque/listar_saida', SaidaListView.as_view(), name="listar_saida"),
    path('estoque/listar_entrada', EntradaListView.as_view(), name="listar_entrada"),

    #URLS dos clientes
    path('cliente/', c.ClientListView.as_view(), name="clientes"),
    path ('cadastrar_cliente', c.ClientCreateView.as_view(), name="cadastrar_cliente"),
    path('atualiza_cliente/<int:pk>', c.ClientUpdateView.as_view(), name="atualiza_cliente"),
    path('delete_cliente/<int:pk>', c.ClientDeleteView.as_view(), name="delete_cliente"),

    #URLS dos serviços
      path('servico/', s.ordem_servico_list, name='home_servicos'),  # noqa E501
      path('servico/cadastrar_ordemservico', s.OrdenServicoCreateView.as_view(), name='ordem_servico_create'),  # criacao do serviço
      path('visualizar_os/<int:pk>', s.ordem_servico_detail, name="visualizar_os"),
      path('servico/criar', s.ServicoCreateView.as_view(), name="cadastrar_servico"),
      path('servico/finalizar_os/<int:pk>', s.OrdenServicoUpdateView.as_view(), name="finalizar_os"),

    #URLS ORÇAMENTO
    path('orcamento/<int:id>/', t.orcamento, name='orcamento'),
    path('transacao/listar_orcamentos/', t.TransacaoListView.as_view(), name='listar_orcamento'),
    path('trasancao/<int:id>/', t.transacao_detail, name='visualizar_orcamento'),
    path('delete_orcamento/<int:pk>', t.TransacaoDeleteView.as_view(), name="delete_orcamento"),
    path('transacao/criar_venda', t.VendaCreateView.as_view(), name="cadastrar_venda"),

     #URL FORNECEDOR
    path('cadastro_fornecedor', t.FornecedorCreateView.as_view(), name='cadastrar_fornecedor'),
    path('visualizar_fornecedor', t.FornecedorListView.as_view(), name='listar_fornecedor'),
]

servico/models.py
from django.db import models
from cliente.models import Cliente
from estoque.models import Product

# Create your models here.
class Servico(models.Model):
    servico = models.CharField(verbose_name="Serviço", max_length=150, null=False, blank=False)
    
    #responsavel para mostrar o nome correto no retorno
    def __str__(self):
        return self.servico
    
SITUACAO = (
    ('pe', 'Pendente'),
    ('ca', 'Cancelado'),
    ('an', 'Andamento'),
    ('ap', 'Aprovado'),
)



class OrdemServico(models.Model):
    situacao = models.CharField('Situação', max_length=2, choices=SITUACAO)
    cliente = models.ForeignKey(
        Cliente,
        on_delete=models.SET_NULL,
        verbose_name='cliente',
        related_name='clientes',
        null=True,
        blank=True
    )
    servico = models.ForeignKey(Servico, 
        on_delete=models.CASCADE,
        null=True,
        blank=True
        )
    #produto = models.ForeignKey(Product, 
     #   on_delete=models.CASCADE,
      #  null=True,
       # blank=True
        #)
    #quantidade = models.PositiveIntegerField(verbose_name="quantidade", null=True, blank=True)
    #valor_produto = models.DecimalField('valor Produto', max_digits=10,
    #decimal_places=2, blank=True, default=0)

    #ocultar alguns campos aqui
    valor_custo = models.DecimalField('Valor Custo', max_digits=8, decimal_places=2, null=True, blank=True, default=0)
    valor_lucro = models.DecimalField('Valor Lucro', max_digits=8, decimal_places=2, null=True, blank=True, default=0)
    data = models.DateTimeField('Data do Serviço', auto_now_add=True, null=True, blank=True )
    observacao = models.TextField('Observação', null=True, blank=True)
    valor = models.DecimalField('Valor total', max_digits=10,
    decimal_places=2, blank=True, default=0)
    solucao = models.TextField('Solução', null=True, blank=True)
    data_termino = models.DateTimeField('Data do Término', null=True, blank=True )

    def save(self, *args, **kwargs):
        #pega o campo saldo n
        self.valor_lucro = self.valor - self.valor_custo
        return super(OrdemServico, self).save(*args, **kwargs)


    def __str__(self):
        return self.servico.servico



    

    


     
    





servico/forms.py
from django import forms

from .models import OrdemServico

#fields = ["servico","cliente","situacao","data","observacao","valor_custo","valor"]

class OrdemServicoForm(forms.ModelForm):
    servico = forms.Select()
    valor = forms.DecimalField()
    data = forms.DateField(
        label='Data: ',
        required=False,
        widget=forms.DateInput(
            format='%Y-%m-%d',
            attrs={
                'type': 'date',
                'class': 'form-control'
            }),
        input_formats=('%Y-%m-%d',),
    )
    observacao = forms.Textarea()
    valor_custo = forms.DecimalField()

    class Meta:
        model = OrdemServico
        fields = ('situacao','cliente','servico','valor','valor_custo','observacao')

    

servico/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from datetime import datetime
from .forms import OrdemServicoForm, forms
from datetime import timedelta
from django.views import generic
from servico.forms import OrdemServicoForm
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView

#from .forms import OrdemServicoForm
from .models import OrdemServico, Servico


def ordem_servico_list(request):

    
    template_name = 'servico/ordem_servico_list.html'
    object_list = OrdemServico.objects.all()

    search = request.GET.get('search')
    if search:
        object_list = object_list.filter(situacao=search)

    context = {'object_list': object_list}
    return render(request, template_name, context)


#class para fazer alterações no cliente
class OrdenServicoUpdateView(SuccessMessageMixin,UpdateView):
    model = OrdemServico
    fields = ["situacao","solucao","valor_custo","valor","data_termino"]

    def get_success_url(self):
        return reverse_lazy('home_servicos')

    def get_context_data(self, **kwargs):
        contexto = super(OrdenServicoUpdateView, self).get_context_data(**kwargs)
        contexto['action'] = reverse_lazy('home_servicos')
        return contexto

    success_message = 'Ordem de serviço finalizada!'



class OrdenServicoCreateView(SuccessMessageMixin,CreateView):
    model = OrdemServico
   # template_name = 'formulario_os.html'
    fields = ["servico","cliente","situacao","observacao"]
    
    def get_success_url(self):
        return reverse_lazy('home_servicos')

    def get_context_data(self, **kwargs):
        contexto = super(OrdenServicoCreateView, self).get_context_data(**kwargs)
        contexto['action'] = reverse_lazy('home_servicos')
        return contexto
    success_message = 'Ordem de serviço criada com sucesso!'


'''class FormularioOS(CreateView, forms.ModelForm):
    servico = forms.Select()
    situacao = forms.Select()

    class Meta:
        model = OrdemServico
        fields = [
            'servico',
            'situacao'
        ]'''


def form_ordenservico(request):
    
    if request.method == "GET":
        form = OrdemServicoForm()
        context = {
            'form': form
        }
        return render(request, "servico/formulario_os.html", context=context)
    else:
        form = OrdemServicoForm(request.POST)
        if form.is_valid():
            ordenservico = form.save()
            form = OrdemServicoForm()
        
        context = {
            'form': form
        }
        return render(request, "servico/formulario_os.html", context=context)


def ordem_servico_detail(request, pk):

    template_name = 'servico/ordem_servico_detail.html'
    instance = OrdemServico.objects.get(pk=pk)  
   
    context = {'object': instance,   
    }


    return render(request, template_name, context)


class ServicoCreateView(CreateView):
    model = Servico
    fields = ["servico"]
    success_url = reverse_lazy("home")


#


#class RelatorioServicoListView(generic.ListView):

 #   queryset = OrdemServico.objects.filter(creation_date__gte=datetime.today()-timedelta(days=30))
  #  context_object_name = 'osss'
   # template_name = 'relatorio_os.html'

templates/servico/formulario_os.html
<!-- ordem_servico_form.html -->
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags%}

{% block title %}Formulário de serviço{% endblock title %}


{% block conteudo %}
<div class="container">
    <br>
    <h4>Cadastrar serviço</h4>
    <form method="POST">
      {% csrf_token %}
      {{ form | crispy }}
      <button type="submit" class="btn btn-primary">Salvar</button>
    </form>
</div>
{% endblock conteudo %}


templates/servico/ordem_servico_detail.html
<!-- ordem_servico_detail.html -->
{% extends "base.html" %}
{% block title %}Detalhes Os{% endblock title %}

{% block conteudo %}
<br><br>
<div class="container">
  <main class="container">
    <div class="row">
        <div class="col-sm-12">
          
          <div class="card">

            <div class="card-body">
              <table class="table">
                
                  <tr>
                    <th> <img src="/static/img/check-box_6399627.png" height="50" width="50">
                    
                      <h4>OS Nº: {{ object.pk }}</h4>
                    Cliente: {{ object.cliente }}<br>
                    <label>Endereço: {{ object.cliente.endereco }}</label><br>
                    <label>Telefone: {{ object.cliente.telefone }}</label><br>
                    <label> {{ object.cliente.cpf }}</label>
                    </th>
                    <th></th>
                    <th>{{ object.get_situacao_display }}</th>
                    <th>Data: {{ object.data|date:"d/m/Y" }}</th>
                  </tr>
               
                <tbody>
                
                    <tr>
                      <td>Serviço: {{ object.servico.servico }}</td>
                      <td></td>
                      <td></td>
                      <td> </td>
                      
                    </tr>
                   
                    
                <tr>
                 
                  <td>
                    Observação: {{object.observacao}}
                  </td>
                  <TD></TD>
                  <TD></TD>
                  <TD></TD>
                </tr>
               <TR>
                
                <TD>Conclusão: {{ object.solucao }}</TD>
                <TD</TD>
                <TD></TD>
                <TD></TD>
                <TD></TD>
               </TR>
               <TR>
                <TD></TD>
                <TD>__________________________________</TD>
                <TD></TD>
                <TD></TD>
                <TD></TD>
               </TR>
               <TR>
                <TD></TD>
                <TD>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Local Certo &nbsp;
                  {%if object.data_termino%}
                    Finalizado em: {{ object.data_termino|date:"d/m/Y" }}</TD>
                  {%endif%}
                    <TD></TD>
                <TD></TD>
               </TR>
              
              </table>
             
              
              
            </div> 
          
          </div><br>
         
          <a href="{% url 'finalizar_os' pk=object.pk %}" class="btn btn-primary btn-sm">Cadastrar Solução</a>
          
        </div>
      </div>
  
</div>
{% endblock conteudo %}

templates/servico/ordem_servico_form.html
<!-- ordem_servico_form.html -->
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags%}
{% block title %}Formulário de serviços{% endblock title %}



{% block conteudo %}
<form method="POST">
  {% csrf_token %}
  {{ form | crispy}}
  <button type="submit" class="btn btn-primary">Salvar</button>
</form>
{% endblock conteudo %}


templates/servico/ordem_servico_list.html
<!-- ordem_servico_list.html -->
{% extends "base.html" %}
{% block title %}Listar OS{% endblock title %}
{% block conteudo %}
<div class="container">
  {% if messages %}
             
  <ul class="messages">
    
      {% for message in messages %}
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>{{ message }}</strong> 
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endfor %}
  </ul>
  
  {% endif %}
  <h4>Ordens de Serviço</h4>

  <a
    href="{% url 'ordem_servico_create' %}"
    class="btn btn-primary"
  >Adicionar</a>

  <div class="row mt-3">
    <div class="col-sm-2">
      <h3>Situação</h3>
      <div class="list-group">
        <a
          href="{% url 'home_servicos' %}"
          class="list-group-item list-group-item-action"
        >
          Limpar filtro
        </a>
        <a
          href="{% url 'home_servicos' %}?search=pe"
          class="list-group-item list-group-item-action"
        >
          Pendente
        </a>
        <a
          href="{% url 'home_servicos' %}?search=ca"
          class="list-group-item list-group-item-action"
        >
          Cancelado
        </a>
        <a
          href="{% url 'home_servicos' %}?search=an"
          class="list-group-item list-group-item-action"
        >
          Andamento
        </a>
        <a
          href="{% url 'home_servicos' %}?search=ap"
          class="list-group-item list-group-item-action"
        >
          Aprovado
        </a>
      </div>

    </div>
    <div class="col-sm-10">
      <table class="table table-dark">
        <thead>
          <tr>
            <th>Num</th>
            <th>Cliente</th>
            <th>Situação</th>
            <th>Serviço</th>
            <th>Valor</th>
            <th>Ações</th>
          </tr>
        </thead>
        <tbody>
          {% for object in object_list %}
            <tr>
              <td>{{ object.pk }}</td>
              <td>
               {{ object.cliente.nome }}
              </td>
              <td>{{ object.get_situacao_display }}</td>
              <td>{{ object.servico.servico }}</td>
              <td>R$: {{ object.valor }}</td>
              
              <td>
               <a href="{% url 'visualizar_os' pk=object.pk %}" class="btn btn-light btn-sm">Visualizar</a>
             </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock conteudo %}

templates/servico/ordemservico_form.html
<!-- ordem_servico_form.html -->
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags%}

{% block title %}Formulário de serviços{% endblock title %}


{% block conteudo %}
<div class="container">
    <br>
    <br>
    {%if object.pk %}
        <a href="{% url 'visualizar_os' pk=object.pk %}" class="btn btn-info">Voltar OS</a>
        <br>    <br> 
    {%endif%}
<h4>Cadastrar OS</h4>
  
    <form method="POST">
            {% csrf_token %}
            {{ form | crispy}}
            <br>
            
            
            <button type="submit" class="btn btn-primary">SALVAR</button>
        </form>
        
</div>
<br>
<br>
{% endblock conteudo %}

<!--
    <div id="div_id_data" class="mb-3">
                <label class="form-label" for="id_cliente">Data inicial</label>
                <input type="date" id="id_data" class="dateinput form-control" name="data">
            </div>
-->

templates/servico/servico_form.html
<!-- ordem_servico_form.html -->
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags%}

{% block title %}Formulário de serviço{% endblock title %}


{% block conteudo %}
<div class="container">
    <br>
    <h4>Cadastrar serviço</h4>
    <form method="POST">
      {% csrf_token %}
      {{ form | crispy}}
      <button type="submit" class="btn btn-primary">Salvar</button>
    </form>
</div>
{% endblock conteudo %}
